/**
 * Songs bundled with the app so every practice mode works before an API key is
 * set up. These are short public-domain / traditional melodies plus a couple of
 * generic progressions, transcribed by hand.
 */
import {Song} from './song';

function song(s: Omit<Song, 'id' | 'createdAt' | 'builtIn'>): Song {
  return {...s, id: 'demo-' + s.title.toLowerCase().replace(/\W+/g, '-'), createdAt: 0, builtIn: true};
}

export const DEMO_SONGS: Song[] = [
  song({
    title: 'House of the Rising Sun',
    artist: 'Traditional',
    keyText: 'A minor',
    tempo: 76,
    timeSignature: [6, 8],
    sections: [
      {
        name: 'Verse',
        chords: [
          {symbol: 'Am', beats: 6},
          {symbol: 'C', beats: 6},
          {symbol: 'D', beats: 6},
          {symbol: 'F', beats: 6},
          {symbol: 'Am', beats: 6},
          {symbol: 'C', beats: 6},
          {symbol: 'E7', beats: 6},
          {symbol: 'E7', beats: 6},
        ],
        melody: [
          {note: 'A3', beats: 1, lyric: 'There'},
          {note: 'C4', beats: 1, lyric: 'is'},
          {note: 'E4', beats: 1, lyric: 'a'},
          {note: 'A4', beats: 2, lyric: 'house'},
          {note: 'G4', beats: 1, lyric: 'in'},
          {note: 'E4', beats: 2, lyric: 'New'},
          {note: 'C4', beats: 1, lyric: 'Or-'},
          {note: 'E4', beats: 3, lyric: 'leans'},
          {note: 'D4', beats: 1, lyric: 'They'},
          {note: 'F4', beats: 1, lyric: 'call'},
          {note: 'A4', beats: 1, lyric: 'the'},
          {note: 'A4', beats: 2, lyric: 'Ris-'},
          {note: 'G4', beats: 1, lyric: 'ing'},
          {note: 'E4', beats: 3, lyric: 'Sun'},
          {note: null, beats: 3},
          {note: 'E4', beats: 1, lyric: "And it's"},
          {note: 'E4', beats: 1, lyric: 'been'},
          {note: 'E4', beats: 1, lyric: 'the'},
          {note: 'G4', beats: 2, lyric: 'ru-'},
          {note: 'E4', beats: 1, lyric: 'in'},
          {note: 'C4', beats: 2, lyric: 'of'},
          {note: 'C4', beats: 1, lyric: 'ma-'},
          {note: 'B3', beats: 3, lyric: 'ny'},
          {note: 'B3', beats: 1, lyric: 'a'},
          {note: 'C4', beats: 1, lyric: 'poor'},
          {note: 'E4', beats: 1, lyric: 'boy'},
          {note: 'E4', beats: 2, lyric: 'and'},
          {note: 'B3', beats: 1, lyric: 'God'},
          {note: 'A3', beats: 3, lyric: 'I'},
          {note: 'A3', beats: 3, lyric: 'know'},
        ],
      },
    ],
    source: {urls: [], confidence: 'high', notes: 'Traditional folk song, bundled with the app.'},
  }),
  song({
    title: 'Scarborough Fair',
    artist: 'Traditional',
    keyText: 'D dorian',
    tempo: 92,
    timeSignature: [3, 4],
    sections: [
      {
        name: 'Verse',
        chords: [
          {symbol: 'Dm', beats: 6},
          {symbol: 'C', beats: 3},
          {symbol: 'Dm', beats: 3},
          {symbol: 'Dm', beats: 3},
          {symbol: 'F', beats: 3},
          {symbol: 'G', beats: 3},
          {symbol: 'Dm', beats: 3},
          {symbol: 'Dm', beats: 3},
          {symbol: 'C', beats: 3},
          {symbol: 'Dm', beats: 6},
        ],
        melody: [
          {note: 'D4', beats: 3, lyric: 'Are'},
          {note: 'A4', beats: 3, lyric: 'you'},
          {note: 'A4', beats: 2, lyric: 'go-'},
          {note: 'E4', beats: 1, lyric: 'ing'},
          {note: 'F4', beats: 1, lyric: 'to'},
          {note: 'G4', beats: 1, lyric: 'Scar-'},
          {note: 'F4', beats: 1, lyric: 'bo-'},
          {note: 'E4', beats: 3, lyric: 'rough'},
          {note: 'D4', beats: 3, lyric: 'Fair'},
          {note: 'A3', beats: 1, lyric: 'Pars-'},
          {note: 'C4', beats: 1, lyric: 'ley'},
          {note: 'D4', beats: 1, lyric: 'sage'},
          {note: 'E4', beats: 3, lyric: 'rose-'},
          {note: 'D4', beats: 3, lyric: 'ma-'},
          {note: 'C4', beats: 3, lyric: 'ry'},
          {note: 'A3', beats: 3, lyric: 'and'},
          {note: 'A3', beats: 3, lyric: 'thyme'},
        ],
      },
    ],
    source: {urls: [], confidence: 'high', notes: 'Traditional, bundled with the app.'},
  }),
  song({
    title: 'Autumn Leaves (changes)',
    artist: 'Joseph Kosma / practice changes',
    keyText: 'G minor',
    tempo: 120,
    timeSignature: [4, 4],
    sections: [
      {
        name: 'A section',
        chords: [
          {symbol: 'Cm7', beats: 4},
          {symbol: 'F7', beats: 4},
          {symbol: 'Bbmaj7', beats: 4},
          {symbol: 'Ebmaj7', beats: 4},
          {symbol: 'Am7b5', beats: 4},
          {symbol: 'D7', beats: 4},
          {symbol: 'Gm', beats: 8},
        ],
        melody: [
          {note: 'G4', beats: 1},
          {note: 'A4', beats: 1},
          {note: 'Bb4', beats: 1},
          {note: 'Eb5', beats: 3},
          {note: null, beats: 1},
          {note: 'F4', beats: 1},
          {note: 'G4', beats: 1},
          {note: 'A4', beats: 1},
          {note: 'D5', beats: 3},
          {note: null, beats: 1},
          {note: 'Eb4', beats: 1},
          {note: 'F4', beats: 1},
          {note: 'G4', beats: 1},
          {note: 'C5', beats: 4},
          {note: 'A4', beats: 2},
          {note: 'F#4', beats: 2},
          {note: 'G4', beats: 4},
          {note: null, beats: 3},
        ],
      },
    ],
    source: {urls: [], confidence: 'medium', notes: 'Standard ii-V-I practice changes, bundled with the app.'},
  }),
  song({
    title: 'Twelve Bar Blues in A',
    artist: 'Practice pattern',
    keyText: 'A mixolydian',
    tempo: 100,
    timeSignature: [4, 4],
    sections: [
      {
        name: 'Chorus',
        chords: [
          {symbol: 'A7', beats: 16},
          {symbol: 'D7', beats: 8},
          {symbol: 'A7', beats: 8},
          {symbol: 'E7', beats: 4},
          {symbol: 'D7', beats: 4},
          {symbol: 'A7', beats: 4},
          {symbol: 'E7', beats: 4},
        ],
        melody: [
          {note: 'A3', beats: 1},
          {note: 'C4', beats: 1},
          {note: 'D4', beats: 1},
          {note: 'D#4', beats: 1},
          {note: 'E4', beats: 2},
          {note: 'D4', beats: 1},
          {note: 'C4', beats: 1},
          {note: 'A3', beats: 4},
          {note: null, beats: 4},
          {note: 'D4', beats: 1},
          {note: 'F4', beats: 1},
          {note: 'G4', beats: 1},
          {note: 'G#4', beats: 1},
          {note: 'A4', beats: 2},
          {note: 'G4', beats: 1},
          {note: 'F4', beats: 1},
          {note: 'D4', beats: 4},
          {note: null, beats: 4},
          {note: 'E4', beats: 2},
          {note: 'D4', beats: 2},
          {note: 'C4', beats: 2},
          {note: 'A3', beats: 2},
          {note: 'E4', beats: 4},
          {note: 'A3', beats: 4},
        ],
      },
    ],
    source: {urls: [], confidence: 'high', notes: 'Standard 12-bar blues, bundled with the app.'},
  }),
];
